# Chapter 06: Counting
본 실습에서는 알고리즘의 복잡도 계산, 경우의 수 계산 등에 필요한 카운팅 수학 기법에 파이썬 구현에 대해 살펴 보기로 한다. 

### Permutation 계산 

![permutation](https://wikimedia.org/api/rest_v1/media/math/render/svg/8edddc122177240d34baebd656f49c30b6f80832)

#### Permutation 구현  Example 01: Page 407

In [24]:
def permutation(n,r): #function definition
    
    i=n
    result=1
    for i in range((n-r)+1,n+1): #computing the permutation
       result=result*i
    
    return result

print("The number of ways to select 3 students from a group of 5 students to line up for a picture is ",permutation(5,3)) #function call
print( "The number of ways to select 5 students from a group of 5 students to line up for a picture is ",permutation(5,5)) #function call


The number of ways to select 3 students from a group of 5 students to line up for a picture is  60
The number of ways to select 5 students from a group of 5 students to line up for a picture is  120


#### Permutation 구현  Example 04: Page 409
How many ways are there to select a first-prize winner, a second-prize winner, and a third-prize
winner from 100 different people who have entered a contest?

#### Iterative algorithm 으로 Permutation 구현 

In [25]:
def permutation(n,r): #function definition    
    i=n
    result=1
    for i in range((n-r)+1,n+1): #permutation computation
       result=result*i
    return result

In [26]:
num=int(input("Enter the number of people: "))
perm=int(input("Enter the prizes: "))
print ("The number of ways to decide the prize winners is ", permutation(num,perm)) #function call

Enter the number of people: 60
Enter the prizes: 1
The number of ways to decide the prize winners is  60


#### Recursive algorithm 으로 Permutation 구현 

In [27]:
def permutation2(n,r):
    if n< r:
        return print(" Please take n greater r")
    if r==0:
        return 1
    return n*permutation(n-1,r-1)

In [28]:
num=int(input("Enter the number of people: "))
perm=int(input("Enter the prizes: "))
print ("The number of ways to decide the prize winners is ", permutation(num,perm)) #function call

Enter the number of people: 60
Enter the prizes: 1
The number of ways to decide the prize winners is  60


####  Factorial 계산을 직접 이용한  permutation 계산     

In [29]:
def factorial(n):
    if n==0:
        return 1
    return n*factorial(n-1)

def permutation3(n,r):
    if n <r : 
        return print(" Please take n greater r")
    if r==0:
        return 1
    return factorial(n)//factorial(n-r)

In [30]:
permutation3(5,3)

60

### Combination 계산 

![combination_wiki](https://wikimedia.org/api/rest_v1/media/math/render/svg/40df4cc626f9492f223b8546145f4c684cd390b7)

In [31]:
def combination(n,r): #combination function
    numerator=1
    denominator=1
    for i in range((n-r)+1,n+1):#computes the value of the numerator 
        numerator=numerator*i
    for j in range (1,r+1): #computes the value of the denominator
        denominator=denominator*j
    result=numerator//denominator #computes result
    return result


In [32]:
num=int(input("Enter the number of elements: "))
comb=int(input("Enter the combinations: "))
print ("The number of combinations are %d."  %(combination(num,comb)))

Enter the number of elements: 60
Enter the combinations: 2
The number of combinations are 1770.


#### Permutation 을 이용한 combination 계산 

In [33]:
def combination(n,r):
    if n< r:
        return print(" Please take n greater r")
    if r==0:
        return 1
    return permutation(n,r)//factorial(r)

In [34]:
combination(5,4)

5

##  "iterable" 객체, "iterator" 객체, "enumerate" 객체를 통한 Counting 

### 파이썬에서의 "iterable" 객체, "iterator" 객체, "enumerate" 객체 
<br>1) 'iterable' 객체는 'for loop' 등에서 저장된 값을 하나씩 처리하는 데 사용된다. 예를 들어 list, tuple, set, dictionary, string, range()로 생성된 객체, numpy array 들은 모두  iterable 객체들이다.  이들은 모두 파이썬의 내장함수 'iter(object[, sentinel])'를 이용해 연관된 "iterator" 객체를 생성할 수 있다. </br><br/>
<br>2)  "iterator" 객체는 셀 수 있는 값들을 포함한 객체로, 저장된 값들을 반복적으로 부를 수 있다. 파이썬에서는 기술적으로, 'iterator protocol' 즉 '__iter__()' 와 '__next__()' 라는 매직 메소드를 구현한 객체이다. </br><br/>
<br>3) 파이썬의 내장함수 'iter(object[, sentinel])' 는 iterator 객체를 생성한다. </br><br/>
<br>4) 'enumerate' 는 'iterable' 객체를 입력으로 받아 인덱스 값을 포함하는 enumerate 객체를 리턴한다. 파이썬의 내장함수  'enumerate(iterable, start=0)' 는 'enumerate' 객체를 생성한다.</br><br/>

In [35]:
str="cat" #iterable 객체 
for c in str:
    print(c)    

c
a
t


In [36]:
str="cat" #iterable 객체
print(str)
myit=iter(str) # itertor 객체 생성 
print(myit)
print(type(myit))
print(next(myit))
print(next(myit))
print(next(myit))
print(next(myit)) # 더 이상 불러 올 게 없어 에러 발생

cat
<class 'str_iterator'>
c
a
t


StopIteration: 

### Iterator 객체 정의 
'__iter__()' 와 '__next__()' 라는 매직 메소드를 구현한 객체이다.

In [37]:
mytuple =  ("apple", "banana", "cherry")
myit = iter(mytuple) # mytuple 를 포함하는 iteror 객체 생성 

print(next(myit))
print(next(myit))
print(next(myit))

apple
banana
cherry


다음은 'iter()' 와 'next()' 라는 매직 메소드를 구현한 Iterator 객체이다.

In [38]:
class MySequence:
    def __init__(self, sequence, start=0): #magic method
        self.sequence=sequence 
        self.start = start
        
    def __iter__(self): #magic method
        print("This is MySequence's iter() method")
        return iter(self.sequence)

    def __next__(self): #magic method
        if self.start==len(self.sequence):
            return -1
        x = self.sequence[self.start]
        self.start += 1
        return x

myseq=("apple", "banana", "cherry")
#myseq=[[1,2,3],[4,5,6],[7,8,9]]
#myseq="Cat"
#import numpy as np
#myseq=np.arange(3)
myclass=MySequence(myseq)
myiter=iter(myclass) # MySequence를 통해 myseq에 대한 iterator 객체를 반환했음을 주의한다.

print(type(myclass))
print(type(myiter))

for i in range(4) : 
    print(next(myclass))
    print(next(myiter)) # 4번 반복 시 StopIteration 발생    

This is MySequence's iter() method
<class '__main__.MySequence'>
<class 'tuple_iterator'>
apple
apple
banana
banana
cherry
cherry
-1


StopIteration: 

In [39]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
for c in a:
    print(c)

[1 2 3]
[4 5 6]
[7 8 9]


### enumerate 객체 
#### 파이썬 내장함수 'enumerate() ' 는 sequence 객체를 받아 generator 객체를 생성한다. 

In [40]:
mySeq = ("apple", "banana", "cherry")
myEnu = enumerate(mytuple) # mytuple 를 포함하는 enumerate 객체 생성 
print(type(myEnu))
print(next(myEnu))
print(next(myEnu))
print(next(myEnu))
print(next(myEnu))

<class 'enumerate'>
(0, 'apple')
(1, 'banana')
(2, 'cherry')


StopIteration: 

In [44]:
mySeq = ("apple", "banana", "cherry")
for i, w in enumerate(mySeq): 
    print(i, w)

0 apple
1 banana
2 cherry


In [45]:
mySeq = ("apple", "banana", "cherry")
myEnu=enumerate(mySeq)
print(list(myEnu))

[(0, 'apple'), (1, 'banana'), (2, 'cherry')]


### 파이썬 내장 함수, 'enumerate()' 는 대략 다음 함수와 비슷하다. 

In [46]:
def enumerate2(sequence, start=0):
    n = start
    for elem in sequence:
        yield n, elem
        n += 1

In [48]:
mySeq = ("apple", "banana", "cherry")
myEnu=enumerate2(mySeq)
print(type(myEnu))
print(next(myEnu))
print(next(myEnu))
print(next(myEnu))
print(next(myEnu))

<class 'generator'>
(0, 'apple')
(1, 'banana')
(2, 'cherry')


StopIteration: 

### Generator 
Generator 는 호출 시에 동작을 재개하여 이터레이팅(순회)이 가능한 'generator'('generator iterator')로 알려진 객체를 반환하는 함수이다. 리스트 등과 달리,  'next()' method 가 호출될 때, 내부적으로 'yield' statement 를 통해 요소를 하나씩 생성을 수행한다. 보관하고 있는 요소가 모두 'next()' 메소드 호출로 생성되면 이후 호출은 StopIteration exception 이 발생한다. 




In [49]:
def odds():
    """Generate odd integers, starting with 1."""
    n = 1
    while True:
        yield n
        n += 2

In [50]:
odds = odds()
list(next(odds) for _ in range(5))

[1, 3, 5, 7, 9]

In [51]:
print(type(range(5)))

<class 'range'>


<h3 style="line-height:1.7em"> Itertools 은 'iterable' 객체를 처리하여 looping (순회)를 통한 문제 처리를 편하게 지원하는 함수들을 지원하며, Counting 과 관련하여서는 'Combinatorics' 관련 함수들이 제공된다. </h3>

#### itertools 모듈의 'count(start=0, step=1)' 함수는 infinite iterator 를 생성한다. 

In [52]:
import itertools as it
odds = it.count(start=1, step=2)
list(next(odds) for _ in range(5))

[1, 3, 5, 7, 9]

#### itertools 모듈은 Combinatoric iterators 관련하여  다음 함수들을 제공한다. 
permutations(iterable, r=None), combinations(iterable, r), combinations_with_replacement(iterable, r)

#### itertools 모듈의 permutations(iterable, r=None) 은 다음과 같이 사용된다. 

In [53]:
import itertools as it
a=tuple([['A', 'B' , 'C'], ['D'], ['E']])
print(type(it.permutations(a, r=2)))
list(it.permutations(a, r=2))

<class 'itertools.permutations'>


[(['A', 'B', 'C'], ['D']),
 (['A', 'B', 'C'], ['E']),
 (['D'], ['A', 'B', 'C']),
 (['D'], ['E']),
 (['E'], ['A', 'B', 'C']),
 (['E'], ['D'])]

#### itertools 모듈의 permutations(iterable, r=None) 은 대략 다음 함수와 유사하다. 

In [54]:
def permutations(iterable, r=None):
    # permutations('ABCD', 2) --> AB AC AD BA BC BD CA CB CD DA DB DC
    # permutations(range(3)) --> 012 021 102 120 201 210
    pool = tuple(iterable)
    n = len(pool)
    r = n if r is None else r
    if r > n:
        return
    
    # Create indice for orders. -> Mix it so that there is no overlap.
    indices = list(range(n))
    # Cycles will generate the mixing
    cycles = list(range(n, n-r, -1))
    
    # yield the first permutation set
    yield tuple(pool[i] for i in indices[:r])
    
    # We will use the yield and return statements
    while n:
        # outside 'i' equals 
        for i in reversed(range(r)):
            cycles[i] -= 1
            if cycles[i] == 0:
#                 print("\n@ Cycle ticks,", cycles, ": Send the", i, "th element of list to the back.")
#                 print("@ indices:", indices, "\tindices[i+1:] :", indices[i+1:], "\tindices[i:i+1] :", indices[i:i+1])
                indices[i:] = indices[i+1:] + indices[i:i+1]
#                 print("@ - Make the indices :", indices)
                cycles[i] = n - i
#                 print("@ Initialize the cycles,", cycles)
            else:
#                 print("\n* Mix the subset(indices[:", r, "]), by change the values, indices[i] :", indices[i], "indices[-cycles[i]] :", indices[-cycles[i]])
                j = cycles[i]
                indices[i], indices[-j] = indices[-j], indices[i]
#                 print("* - result :", indices, "return :", tuple(pool[i] for i in indices[:r]))
                yield tuple(pool[i] for i in indices[:r])
                break
        else:
            return

In [55]:
a='ABCD'
list(permutations(a, r=3))

[('A', 'B', 'C'),
 ('A', 'B', 'D'),
 ('A', 'C', 'B'),
 ('A', 'C', 'D'),
 ('A', 'D', 'B'),
 ('A', 'D', 'C'),
 ('B', 'A', 'C'),
 ('B', 'A', 'D'),
 ('B', 'C', 'A'),
 ('B', 'C', 'D'),
 ('B', 'D', 'A'),
 ('B', 'D', 'C'),
 ('C', 'A', 'B'),
 ('C', 'A', 'D'),
 ('C', 'B', 'A'),
 ('C', 'B', 'D'),
 ('C', 'D', 'A'),
 ('C', 'D', 'B'),
 ('D', 'A', 'B'),
 ('D', 'A', 'C'),
 ('D', 'B', 'A'),
 ('D', 'B', 'C'),
 ('D', 'C', 'A'),
 ('D', 'C', 'B')]

#### itertools 모듈의 combinations(iterable, r) 은 다음과 같이 사용된다. 

In [56]:
import itertools as it
a=tuple([['A', 'B' , 'C'], ['D'], ['E']])
print(type(it.combinations(a, r=2)))
list(it.combinations(a, r=2))

<class 'itertools.combinations'>


[(['A', 'B', 'C'], ['D']), (['A', 'B', 'C'], ['E']), (['D'], ['E'])]

#### itertools 모듈의 combinations(iterable, r) 은 대략 다음 함수와 유사하다. 

In [57]:
def combinations2(iterable, r):
    # combinations('ABCD', 2) --> AB AC AD BC BD CD
    # combinations(range(4), 3) --> 012 013 023 123
    pool = tuple(iterable)
    n = len(pool)
    if r > n:
        return
    indices = list(range(r))
    yield tuple(pool[i] for i in indices)
    while True:
        for i in reversed(range(r)):
            if indices[i] != i + n - r:
                break
        else:
            return
        indices[i] += 1
        for j in range(i+1, r):
            indices[j] = indices[j-1] + 1
        yield tuple(pool[i] for i in indices)

In [58]:
a=tuple([['A', 'B' , 'C'], ['D'], ['E']])
print(type(combinations2(a, r=2)))
list(combinations(a, r=2))

<class 'generator'>


NameError: name 'combinations' is not defined

#### itertools 모듈의 combinations_with_replacements(iterable, r) 은 다음과 같이 사용된다. 

In [59]:
a='ABCD'
list(combinations_with_replacement(a, r=2))

NameError: name 'combinations_with_replacement' is not defined

#### itertools 모듈의 combinations_with_replacement(iterable, r) 은 대략 다음 함수와 유사하다. 

In [60]:
def combinations_with_replacement2(iterable, r):
    # combinations_with_replacement('ABC', 2) --> AA AB AC BB BC CC
    pool = tuple(iterable)
    n = len(pool)
    if not n and r:
        return
    indices = [0] * r
    yield tuple(pool[i] for i in indices)
    while True:
        for i in reversed(range(r)):
            if indices[i] != n - 1:
                break
        else:
            return
        indices[i:] = [indices[i] + 1] * (r - i)
        yield tuple(pool[i] for i in indices)

In [61]:
a='ABCD'
list(combinations_with_replacement2(a, r=2))

[('A', 'A'),
 ('A', 'B'),
 ('A', 'C'),
 ('A', 'D'),
 ('B', 'B'),
 ('B', 'C'),
 ('B', 'D'),
 ('C', 'C'),
 ('C', 'D'),
 ('D', 'D')]

In [62]:

def combinations_with_replacement3(iterable, r):
    # combinations_with_replacement('ABC', 2) --> AA AB AC BB BC CC
    pool = tuple(iterable)
    n = len(pool)
    if not n and r:
        return
    indices = [0] * r
    yield tuple(pool[i] for i in indices)
    while True:
        for i in reversed(range(r)):
            if indices[i] != n - 1:
                break
        else:
            return
        indices[i:] = [indices[i] + 1] * (r - i)      
        yield tuple(pool[i] for i in indices)

In [63]:
pool='ABCD'
r=3
list(combinations_with_replacement3(pool, r))

[('A', 'A', 'A'),
 ('A', 'A', 'B'),
 ('A', 'A', 'C'),
 ('A', 'A', 'D'),
 ('A', 'B', 'B'),
 ('A', 'B', 'C'),
 ('A', 'B', 'D'),
 ('A', 'C', 'C'),
 ('A', 'C', 'D'),
 ('A', 'D', 'D'),
 ('B', 'B', 'B'),
 ('B', 'B', 'C'),
 ('B', 'B', 'D'),
 ('B', 'C', 'C'),
 ('B', 'C', 'D'),
 ('B', 'D', 'D'),
 ('C', 'C', 'C'),
 ('C', 'C', 'D'),
 ('C', 'D', 'D'),
 ('D', 'D', 'D')]